import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  scroll: { padding: 24, flexGrow: 1 },
  title: { fontSize: 32, fontWeight: 'bold', color: '#28a745', marginBottom: 8 },
  subtitle: { fontSize: 16, color: '#666', marginBottom: 20 },
  card: { backgroundColor: '#fff', padding: 20, borderRadius: 12, elevation: 2, marginBottom: 20 },
  sectionTitle: { fontSize: 20, fontWeight: 'bold', color: '#333', marginBottom: 8 },
  infoText: { fontSize: 16, color: '#666', marginBottom: 12 },
  progressBar: { height: 12, backgroundColor: '#e9ecef', borderRadius: 6, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: '#28a745' },
  input: { backgroundColor: '#f8f9fa', borderWidth: 1, borderColor: '#ddd', borderRadius: 8, padding: 12, fontSize: 18, marginBottom: 12 },
  actionButton: { backgroundColor: '#28a745', padding: 18, borderRadius: 12, alignItems: 'center' },
  actionButtonText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  actionButtonSecondary: { backgroundColor: '#fff', borderWidth: 2, borderColor: '#28a745', padding: 18, borderRadius: 12, alignItems: 'center', marginBottom: 20 },
  actionButtonTextSecondary: { color: '#28a745', fontSize: 18, fontWeight: 'bold' },
  backButton: { backgroundColor: '#dc3545', padding: 16, borderRadius: 12, alignItems: 'center', marginTop: 'auto' },
  backButtonText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  historyContainer: { padding: 16, backgroundColor: '#fff', borderRadius: 12, borderWidth: 1, borderColor: '#eee', marginBottom: 20 },
  historyTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 8 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { width: '90%', maxHeight: '80%', backgroundColor: '#fff', borderRadius: 12, padding: 20 },
  modalTitle: { fontSize: 24, fontWeight: 'bold', color: '#28a745', marginBottom: 16 },
  exerciseItem: { marginBottom: 16, borderBottomWidth: 1, borderBottomColor: '#eee', paddingBottom: 16 },
  exerciseName: { fontSize: 18, fontWeight: 'bold', color: '#333', marginBottom: 4 },
  exerciseDesc: { fontSize: 14, color: '#666', lineHeight: 20 },
  closeModalBtn: { backgroundColor: '#dc3545', padding: 16, borderRadius: 12, alignItems: 'center', marginTop: 10 },
  closeModalText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  activityList: { marginBottom: 10 },
  activityButton: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#ddd', borderRadius: 12, padding: 18, marginBottom: 12, alignItems: 'center' },
  selectedActivityButton: { borderColor: '#28a745', backgroundColor: '#e6ffe6' },
  activityText: { fontSize: 18, color: '#333', fontWeight: '500' },
  selectedActivityText: { color: '#28a745', fontWeight: 'bold' }
});
