import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  scroll: {
    padding: 24,
    flexGrow: 1,
  },
  title: {
    fontSize: 32,
    fontWeight: '800',
    color: '#1E293B',
    marginBottom: 8,
    marginTop: 20,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 16,
    color: '#475569',
    marginBottom: 30,
    lineHeight: 24,
  },
  formGroup: {
    marginBottom: 20,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  label: {
    fontSize: 16,
    fontWeight: '700',
    color: '#334155',
    marginBottom: 8,
  },
  input: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 16,
    fontSize: 16,
    color: '#1E293B',
  },
  genderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
  },
  genderButton: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 12,
    borderRadius: 16,
    marginHorizontal: 4,
    alignItems: 'center',
  },
  selectedGender: {
    borderColor: '#0F172A',
    backgroundColor: '#F1F5F9',
  },
  genderText: {
    fontSize: 15,
    color: '#64748B',
    fontWeight: '600',
  },
  selectedGenderText: {
    color: '#0F172A',
    fontWeight: '800',
  },
  imcContainer: {
    backgroundColor: '#F8FAFC',
    padding: 20,
    borderRadius: 16,
    alignItems: 'center',
    marginBottom: 30,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  imcTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1E293B',
  },
  imcClass: {
    fontSize: 20,
    color: '#0F172A',
    fontWeight: '800',
    marginTop: 4,
  },
  saveButton: {
    backgroundColor: '#0056b3',
    borderRadius: 12,
    padding: 18,
    alignItems: 'center',
    marginTop: 'auto',
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  backButton: {
    backgroundColor: '#64748B',
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    marginTop: 10,
  },
  backButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  sectionTitle: { fontSize: 20, fontWeight: '800', color: '#1E293B', marginTop: 10, marginBottom: 15 },
  card: { backgroundColor: 'rgba(255, 255, 255, 0.85)', padding: 24, borderRadius: 24, marginBottom: 20, elevation: 3, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 12 },
  activityList: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  activityButton: { flex: 1, minWidth: '45%', backgroundColor: 'rgba(255, 255, 255, 0.95)', padding: 14, borderRadius: 16, alignItems: 'center', borderWidth: 1, borderColor: '#E2E8F0' },
  selectedActivityButton: { backgroundColor: '#F1F5F9', borderColor: '#0F172A' },
  activityText: { fontSize: 14, color: '#64748B', textAlign: 'center', fontWeight: '600' },
  selectedActivityText: { color: '#0F172A', fontWeight: '800' },
  infoText: { fontSize: 16, color: '#475569', marginBottom: 10 },
  progressBar: { height: 12, backgroundColor: '#E2E8F0', borderRadius: 6, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: '#0F172A' },
  actionButton: { backgroundColor: '#0F172A', padding: 16, borderRadius: 16, alignItems: 'center', marginTop: 10, shadowColor: '#0F172A', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 8 },
  actionButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  historyContainer: { marginTop: 10, marginBottom: 20 },
  historyTitle: { fontSize: 20, fontWeight: '800', color: '#1E293B', marginBottom: 10 },
  actionButtonSecondary: { backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#E2E8F0', padding: 16, borderRadius: 16, alignItems: 'center', marginBottom: 20 },
  actionButtonTextSecondary: { color: '#1E293B', fontSize: 16, fontWeight: 'bold' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: '#fff', borderTopLeftRadius: 32, borderTopRightRadius: 32, padding: 32, maxHeight: '85%' },
  modalTitle: { fontSize: 24, fontWeight: '800', color: '#1E293B', marginBottom: 24, textAlign: 'center' },
  exerciseItem: { borderBottomWidth: 1, borderBottomColor: '#F1F5F9', paddingVertical: 16 },
  exerciseName: { fontSize: 18, fontWeight: '800', color: '#0F172A', marginBottom: 6 },
  exerciseDesc: { fontSize: 16, color: '#475569', lineHeight: 24 },
  closeModalBtn: { backgroundColor: '#0F172A', padding: 18, borderRadius: 16, alignItems: 'center', marginTop: 24 },
  closeModalText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
});

