import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  scroll: {
    padding: 24,
    flexGrow: 1,
  },
  header: {
    marginBottom: 32,
    alignItems: 'center',
    marginTop: 20,
  },
  title: {
    fontSize: 34,
    fontWeight: '800',
    color: '#1A1A24',
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 16,
    color: '#8A8A99',
    marginTop: 8,
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1A1A24',
    marginBottom: 20,
    letterSpacing: -0.3,
  },
  moodGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 32,
    gap: 16,
  },
  moodCard: {
    width: '47%',
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: 24,
    paddingVertical: 24,
    paddingHorizontal: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  emojiContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#F0F0F5',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emoji: {
    fontSize: 32,
  },
  moodLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A4A5C',
  },
  activityContainer: {
    marginBottom: 32,
  },
  activityScroll: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  activityChip: {
    backgroundColor: '#F0F0F5',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  activityChipSelected: {
    backgroundColor: '#E8E8F0',
    borderColor: '#1A1A24',
  },
  activityChipText: {
    color: '#4A4A5C',
    fontSize: 15,
    fontWeight: '600',
  },
  activityChipTextSelected: {
    color: '#1A1A24',
    fontWeight: '700',
  },
  saveButton: {
    backgroundColor: '#1A1A24',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#1A1A24',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 5,
    marginBottom: 24,
  },
  saveButtonDisabled: {
    backgroundColor: '#E0E0E5',
    shadowOpacity: 0,
    elevation: 0,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  historyContainer: {
    marginTop: 10,
    marginBottom: 30,
  },
  historyTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1A1A24',
    marginBottom: 16,
    letterSpacing: -0.3,
  },
  historyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 2,
  },
  historyEmojiContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  historyEmoji: {
    fontSize: 24,
  },
  historyContent: {
    flex: 1,
  },
  historyDate: {
    fontSize: 14,
    color: '#8A8A99',
    marginBottom: 4,
    fontWeight: '500',
  },
  historyMoodName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A24',
    textTransform: 'capitalize',
  },
  historyActivity: {
    fontSize: 14,
    color: '#666',
    marginTop: 2,
  },
  emptyHistory: {
    textAlign: 'center',
    color: '#8A8A99',
    fontSize: 16,
    marginTop: 20,
    fontStyle: 'italic',
  },
  backButton: {
    padding: 16,
    alignItems: 'center',
    borderRadius: 16,
    backgroundColor: '#F0F0F5',
  },
  backButtonText: {
    color: '#4A4A5C',
    fontSize: 16,
    fontWeight: '600',
  }
});
