import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  header: { padding: 20, paddingTop: 40, paddingBottom: 10 },
  title: { fontSize: 32, fontWeight: 'bold', color: '#333' },
  newButton: { backgroundColor: '#0056b3', marginHorizontal: 20, marginBottom: 20, borderRadius: 12, padding: 16, alignItems: 'center', elevation: 2 },
  newButtonText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  listContent: { paddingHorizontal: 20, paddingBottom: 20 },
  reminderCard: { flexDirection: 'row', backgroundColor: '#fff', borderRadius: 12, marginBottom: 16, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 2, overflow: 'hidden' },
  colorBar: { width: 6 },
  reminderContent: { flex: 1, flexDirection: 'row', alignItems: 'center', padding: 16 },
  reminderTitle: { fontSize: 18, fontWeight: 'bold', color: '#333', marginBottom: 4 },
  reminderType: { fontSize: 14, color: '#666' },
  timeBadge: { backgroundColor: '#f0f0f0', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, marginRight: 10 },
  timeText: { fontSize: 16, fontWeight: 'bold', color: '#333' },
  deleteButton: { padding: 8 },
  deleteButtonText: { color: '#dc3545', fontSize: 18, fontWeight: 'bold' },
  empty: { textAlign: 'center', color: '#666', fontSize: 16, marginTop: 40 },
  backButton: { backgroundColor: '#dc3545', marginHorizontal: 20, padding: 16, borderRadius: 12, alignItems: 'center', marginTop: 10, marginBottom: 20 },
  backButtonText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: '#fff', padding: 24, borderTopLeftRadius: 24, borderTopRightRadius: 24 },
  modalTitle: { fontSize: 24, fontWeight: 'bold', color: '#333', marginBottom: 20, textAlign: 'center' },
  label: { fontSize: 16, fontWeight: 'bold', color: '#555', marginBottom: 8, marginTop: 12 },
  input: { backgroundColor: '#f8f9fa', borderWidth: 1, borderColor: '#ddd', borderRadius: 12, padding: 16, fontSize: 16 },
  categoryContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 20 },
  categoryBtn: { borderWidth: 1, borderColor: '#ddd', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20 },
  categoryText: { color: '#666' },
  saveModalBtn: { backgroundColor: '#28a745', padding: 18, borderRadius: 12, alignItems: 'center', marginTop: 10 },
  saveModalText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  cancelModalBtn: { padding: 18, alignItems: 'center', marginTop: 5 },
  cancelModalText: { color: '#666', fontSize: 16, fontWeight: 'bold' }
});
