import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAFC',
  },
  scroll: {
    padding: 24,
    flexGrow: 1,
  },
  header: {
    marginBottom: 32,
    alignItems: 'center',
    marginTop: 20,
  },
  title: {
    fontSize: 34,
    fontWeight: '800',
    color: '#1A1A24',
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 16,
    color: '#8A8A99',
    marginTop: 8,
    textAlign: 'center',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 3,
  },
  formGroup: {
    marginBottom: 20,
  },
  labelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  iconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  label: {
    fontSize: 16,
    fontWeight: '700',
    color: '#4A4A5C',
  },
  input: {
    backgroundColor: '#F8F9FA',
    borderWidth: 1.5,
    borderColor: '#E0E0E5',
    borderRadius: 16,
    padding: 16,
    fontSize: 18,
    color: '#1A1A24',
    fontWeight: '600',
  },
  inputFocused: {
    borderColor: '#E63946',
    backgroundColor: '#FFFFFF',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A1A24',
    marginTop: 10,
    marginBottom: 12,
  },
  chipContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 20,
  },
  chip: {
    backgroundColor: '#F0F0F5',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  chipSelected: {
    backgroundColor: '#E63946',
    borderColor: '#E63946',
  },
  chipText: {
    color: '#4A4A5C',
    fontSize: 15,
    fontWeight: '600',
  },
  chipTextSelected: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  exerciseContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  exerciseBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: '#F0F0F5',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  exerciseBtnSelectedYes: {
    backgroundColor: '#D1FAE5',
    borderColor: '#10B981',
  },
  exerciseBtnSelectedNo: {
    backgroundColor: '#FEE2E2',
    borderColor: '#EF4444',
  },
  exerciseBtnText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A4A5C',
  },
  exerciseBtnTextSelectedYes: {
    color: '#065F46',
  },
  exerciseBtnTextSelectedNo: {
    color: '#991B1B',
  },
  saveButton: {
    backgroundColor: '#E63946',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#E63946',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 5,
    marginBottom: 24,
  },
  saveButtonDisabled: {
    backgroundColor: '#E0E0E5',
    shadowOpacity: 0,
    elevation: 0,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  historyContainer: {
    marginTop: 10,
    marginBottom: 30,
  },
  historyTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1A1A24',
    marginBottom: 16,
    letterSpacing: -0.3,
  },
  historyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  historyDateContainer: {
    backgroundColor: '#F0F0F5',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    width: 60,
  },
  historyTime: {
    fontSize: 14,
    fontWeight: '700',
    color: '#4A4A5C',
  },
  historyDate: {
    fontSize: 12,
    color: '#8A8A99',
    marginTop: 2,
  },
  historyContent: {
    flex: 1,
  },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  historyValue: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1A1A24',
    marginLeft: 6,
  },
  emptyHistory: {
    textAlign: 'center',
    color: '#8A8A99',
    fontSize: 16,
    marginTop: 20,
    fontStyle: 'italic',
  },
  backButton: {
    padding: 16,
    alignItems: 'center',
    borderRadius: 16,
    backgroundColor: '#F0F0F5',
  },
  backButtonText: {
    color: '#4A4A5C',
    fontSize: 16,
    fontWeight: '600',
  },
  rowInputs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  rowInputContainer: {
    flex: 1,
  },
  rulerWrapper: {
    height: 120,
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    marginTop: 8,
    marginBottom: 8,
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#E0E0E5',
    overflow: 'hidden',
    position: 'relative',
  },
  rulerContent: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  rulerItem: {
    height: 40,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rulerText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000000ff',
  },
  rulerTextSelected: {
    color: '#E63946',
    fontWeight: '800',
    fontSize: 20,
  },
  pickerIndicator: {
    position: 'absolute',
    top: 40,
    height: 40,
    left: 8,
    right: 8,
    borderTopWidth: 1.5,
    borderBottomWidth: 1.5,
    borderColor: '#E63946',
    backgroundColor: '#E6394605',
    borderRadius: 8,
  },
  glicoseChipsContainer: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
    marginBottom: 8,
  },
  glicoseChip: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E0E0E5',
    backgroundColor: '#F8F9FA',
    alignItems: 'center',
  },
  glicoseChipSelected: {
    backgroundColor: '#3B82F6',
    borderColor: '#3B82F6',
  },
  glicoseChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#4A4A5C',
  },
  glicoseChipTextSelected: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  glicoseLabelContext: {
    fontSize: 14,
    fontWeight: '700',
    color: '#3B82F6',
    marginTop: 4,
  }
});
